// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DirectoryHistory.UI {
    
    
    public partial class HistoryDialog {
        
        private Gtk.VBox entriesVbox;
        
        private Gtk.Label label;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DirectoryHistory.UI.HistoryDialog
            this.Name = "DirectoryHistory.UI.HistoryDialog";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child DirectoryHistory.UI.HistoryDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.entriesVbox = new Gtk.VBox();
            this.entriesVbox.Name = "entriesVbox";
            this.entriesVbox.Spacing = 6;
            // Container child entriesVbox.Gtk.Box+BoxChild
            this.label = new Gtk.Label();
            this.label.Name = "label";
            this.label.LabelProp = Mono.Unix.Catalog.GetString("label1");
            this.entriesVbox.Add(this.label);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.entriesVbox[this.label]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child entriesVbox.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            this.entriesVbox.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.entriesVbox[this.scrolledwindow1]));
            w3.Position = 1;
            w1.Add(this.entriesVbox);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.entriesVbox]));
            w4.Position = 0;
            // Internal child DirectoryHistory.UI.HistoryDialog.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Name = "dialog1_ActionArea";
            w5.Spacing = 10;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
            w6.Expand = false;
            w6.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
