
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action openAction;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action HistoryAction;

	private global::Gtk.Action InfoAction;

	private global::Gtk.Action refreshAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action addAction;

	private global::Gtk.Action applyAction;

	private global::Gtk.Action fileHistoryAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Toolbar toolbar1;

	private global::DirectoryHistory.UI.FolderList folderlist;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label loadedDirectoryLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("openDirectory"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("openDirectory");
		w1.Add (this.openAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.HistoryAction = new global::Gtk.Action ("HistoryAction", global::Mono.Unix.Catalog.GetString ("History"), null, null);
		this.HistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("History");
		w1.Add (this.HistoryAction, null);
		this.InfoAction = new global::Gtk.Action ("InfoAction", global::Mono.Unix.Catalog.GetString ("Info"), null, null);
		this.InfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Info");
		w1.Add (this.InfoAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("refresh"), null, "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("refresh");
		w1.Add (this.refreshAction, "<Control>r");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("quit");
		w1.Add (this.quitAction, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
		w1.Add (this.aboutAction, null);
		this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("_Add"), null, "gtk-add");
		this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Add");
		w1.Add (this.addAction, null);
		this.applyAction = new global::Gtk.Action ("applyAction", global::Mono.Unix.Catalog.GetString ("_Apply"), null, "gtk-apply");
		this.applyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Apply");
		w1.Add (this.applyAction, null);
		this.fileHistoryAction = new global::Gtk.Action ("fileHistoryAction", global::Mono.Unix.Catalog.GetString ("File_History"), null, "gtk-dnd-multiple");
		this.fileHistoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File_History");
		w1.Add (this.fileHistoryAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Directory History");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-find-and-replace", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='HistoryAction' action='HistoryAction'><menuitem name='refreshAction' action='refreshAction'/></menu><menu name='InfoAction' action='InfoAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='openAction' action='openAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='addAction' action='addAction'/><toolitem name='applyAction' action='applyAction'/><toolitem name='fileHistoryAction' action='fileHistoryAction'/><toolitem name='quitAction' action='quitAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(3));
		this.vbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.folderlist = new global::DirectoryHistory.UI.FolderList ();
		this.folderlist.Events = ((global::Gdk.EventMask)(256));
		this.folderlist.Name = "folderlist";
		this.vbox2.Add (this.folderlist);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.folderlist]));
		w4.Position = 1;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w5.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.loadedDirectoryLabel = new global::Gtk.Label ();
		this.loadedDirectoryLabel.Name = "loadedDirectoryLabel";
		this.loadedDirectoryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("No directory loaded");
		this.statusbar1.Add (this.loadedDirectoryLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.loadedDirectoryLabel]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 462;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.addAction.Activated += new global::System.EventHandler (this.OnAddActionActivated);
		this.applyAction.Activated += new global::System.EventHandler (this.OnApplyActionActivated);
		this.fileHistoryAction.Activated += new global::System.EventHandler (this.OnFileHistoryActionActivated);
	}
}
